source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# Specify your gem's dependencies in sinatra-nested-forms-readme-v-000.gemspec
gemspec

gem 'sinatra'
    gem 'rake'
    gem 'thin'
    gem 'shotgun'
    gem 'pry'
    gem 'require_all'
 group :test do
      gem 'rspec'
      gem 'capybara'
      gem 'rack-test'
    end